#!/bin/bash

# OpenClaw WeChat 安装配置脚本
# 用于初始安装和配置

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 脚本目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════╗"
echo "║     OpenClaw WeChat Bridge - Setup Script                  ║"
echo "║     本地部署微信 Bridge 服务配置工具                         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# 检查 Node.js
check_prerequisites() {
    echo -e "${YELLOW}Checking prerequisites...${NC}"

    if ! command -v node &> /dev/null; then
        echo -e "${RED}Error: Node.js is not installed${NC}"
        echo "Please install Node.js 18 or higher:"
        echo "  Ubuntu/Debian: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs"
        echo "  macOS: brew install node"
        echo "  Or visit: https://nodejs.org/"
        exit 1
    fi

    NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        echo -e "${RED}Error: Node.js version must be 18 or higher${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Node.js $(node --version)${NC}"

    if ! command -v npm &> /dev/null; then
        echo -e "${RED}Error: npm is not installed${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ npm $(npm --version)${NC}"
}

# 安装依赖
install_dependencies() {
    echo ""
    echo -e "${YELLOW}Installing dependencies...${NC}"

    if [ -d "node_modules" ]; then
        echo "Dependencies already installed. Skip? (y/n)"
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            return
        fi
    fi

    npm install
    echo -e "${GREEN}✓ Dependencies installed${NC}"
}

# 创建配置文件
setup_config() {
    echo ""
    echo -e "${YELLOW}Setting up configuration...${NC}"

    # 创建 .env 文件
    if [ -f ".env" ]; then
        echo ".env file already exists. Overwrite? (y/n)"
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            echo -e "${GREEN}✓ Keeping existing .env${NC}"
            return
        fi
    fi

    # 默认配置
    DEFAULT_PORT=3001
    DEFAULT_PUPPET="wechaty-puppet-wechat"

    echo ""
    echo "Please configure the following settings (press Enter to use defaults):"
    echo ""

    read -p "Bridge Port [$DEFAULT_PORT]: " PORT
    PORT=${PORT:-$DEFAULT_PORT}

    echo ""
    echo "Select Wechaty Puppet:"
    echo "  1) wechaty-puppet-wechat (default, free)"
    echo "  2) wechaty-puppet-padlocal (requires token)"
    read -p "Choice [1]: " puppet_choice

    case $puppet_choice in
        2)
            PUPPET="wechaty-puppet-padlocal"
            read -p "Enter padlocal token: " PUPPET_TOKEN
            ;;
        *)
            PUPPET="wechaty-puppet-wechat"
            PUPPET_TOKEN=""
            ;;
    esac

    # 创建 .env 文件
    cat > .env << EOF
# OpenClaw WeChat Bridge Configuration
# Generated by setup.sh on $(date)

# HTTP Server
PORT=$PORT
HOST=0.0.0.0

# Wechaty
WECHATY_NAME=openclaw-wechat
WECHATY_PUPPET=$PUPPET
WECHATY_PUPPET_TOKEN=$PUPPET_TOKEN

# Data Storage
WECHATY_MEMORY_CARD_PATH=./data

# Reconnect Settings
WECHATY_RECONNECT_INTERVAL=5000
WECHATY_MAX_RECONNECT_ATTEMPTS=10
WECHATY_HEARTBEAT_INTERVAL=30000

# Cache Settings
WECHATY_CONTACTS_CACHE_TTL=300000

# Logging
LOG_LEVEL=info
EOF

    echo -e "${GREEN}✓ Configuration saved to .env${NC}"
}

# 创建数据目录
setup_directories() {
    echo ""
    echo -e "${YELLOW}Setting up directories...${NC}"

    mkdir -p data
    mkdir -p logs

    echo -e "${GREEN}✓ Directories created${NC}"
}

# 创建启动脚本
setup_scripts() {
    echo ""
    echo -e "${YELLOW}Setting up scripts...${NC}"

    chmod +x start-bridge.sh

    echo -e "${GREEN}✓ Scripts configured${NC}"
}

# 显示完成信息
show_completion() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}Setup completed successfully!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo "To start the Bridge service:"
    echo "  ./start-bridge.sh"
    echo ""
    echo "To start in development mode:"
    echo "  ./start-bridge.sh --dev"
    echo ""
    echo "To configure OpenClaw plugin:"
    echo "  openclaw config set channels.wechat.bridgeUrl \"http://localhost:${PORT:-3001}\""
    echo ""
    echo "For more information:"
    echo "  cat README.md"
    echo ""
}

# 主流程
main() {
    check_prerequisites
    install_dependencies
    setup_config
    setup_directories
    setup_scripts
    show_completion
}

main
